[versions]
kotlin = "1.9.20-RC"
kotlinx-coroutines = "1.7.3"
android = "7.4.2"
androidx-lifecycle = "2.6.1"

# Sample versions
androidx-compose = "2023.06.01"
androidx-compose-compiler = "1.5.4-dev-k1.9.20-RC-1edce5fd625"
androidx-fragment = "1.6.1"
ksp = "1.9.20-RC-1.0.13"
nativecoroutines = "1.0.0-ALPHA-18-kotlin-1.9.20-RC"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }

# Sample libraries
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "android" }

# Sample plugins
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "android" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
nativecoroutines = { id = "com.rickclephas.kmp.nativecoroutines", version.ref = "nativecoroutines" }
