name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  qodana:
    runs-on: macos-14
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: rickclephas/qodana-action@macos
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
